[project]
name = "GameSearch"
version = "0.0.1"
authors = [{ name = "Pedro Moreira", email = "pedro.lucas.rocha72@gmail.com" }]
description = "A Discord bot that allows users to search for games using the IGDB API."
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["igdb-api-v4", "python-dotenv", "requests", "nextcord"]

[project.urls]
Homepage = "https://github.com/RoPedro/GameSearch"
Issues = "https://github.com/RoPedro/GameSearch/issues"
