name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build --tag ${{ vars.IMAGE_NAME }}:latest .
      - name: Login to Dockerhub
        run: docker login -u pedrolrmoreira -p ${{ secrets.DOCKERHUB_TK }}
      - name: Push to dockerhub
        run: docker push ${{ vars.IMAGE_NAME }}
